#defining function will only run when called 
def bbclogo():
    print()
    print("====================================")
    print("====================================")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BBBBBB      BBBBBB      CC        ")
    print("  BB    BB    BB    BB    CC        ")
    print("  BB    BB    BB    BB    CCCCCCCC  ")
    print("  BBBBBB      BBBBBB      CCCCCCCC  ")
    print("====================================")
    print("====================================")
    print()

def displaytime():
    print("========================================")
    print("Welcome to the TV listening program")
    print("Todays date is the:", datetime.strftime("%x"))
    print("Current time:" ,datetime.strftime("%x"))
    print("========================================")
print()
print("Lemons")
print()
#printing it:
bbclogo()
print("EastEnders is a British television soap opera, ")
print("first broadcast on 19 February 1985.")
print("EastEnders storylines examine the domestic and")
print("professional lives of the people who live and work")
print("in the fictional London Borough of Walford in the East End of London.")
print()
input("Press Enter to continue")
